spring:
  data:
    redis:
      host: localhost
      port: 6378
      password: isshoni7
      timeout: 2000

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: 3f60f411225724220d965e0349fa56db
            client-secret: rKPWKpG7EhTCInvm1VIetR94o7fiwIKp
            redirect-uri: http://localhost:8080/oauth2/kakao
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

