services:
  mysql:
    image: mysql:8.0.34
    container_name: isshoniGo-mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./isshonigo-data:/var/lib/mysql
    ports:
      - "3306:3306"

    networks:
      - isshonigo-network

networks:
  isshonigo-network:
    external: true
