name: EC2 CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GH_TOKEN }}

      - name: JDK 17 setting
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Give gradle permission
        run: chmod +x ./gradlew

      - name: Build gradle
        run: ./gradlew clean build

      - name: Login for dockerhub access
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Docker image build, and upload
        run: |
          docker build -t seol7/isshonigo-server:latest -f explorer-external-api/Dockerfile .
          docker push seol7/isshonigo-server:latest

  push:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Repository checkout
        uses: actions/checkout@v3

      - name: docker-compose in EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PEMKEY }}
          port: 22
          script: |
            cd ~/isshonigo/api/theme-explorer-japan-be/infra/app
            docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
            docker-compose -f docker-compose.yml down
            docker-compose -f docker-compose.yml pull
            docker-compose -f docker-compose.yml up -d
