spring:
  profiles:
    group:
      local:
        - domain-local
        - common
      dev:
        - domain-dev
        - common
    active:
      local

# logging:
#  level:
#    org:
#      springframework:
#        web:
#          socket: DEBUG
#      apache:
#        tomcat:
#          websocket: DEBUG
