spring:
  data:
    redis:
      host: isshonigo-redis
      port: 6379
      password: isshoni7
      timeout: 2000

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: 3f60f411225724220d965e0349fa56db
            client-secret: rKPWKpG7EhTCInvm1VIetR94o7fiwIKp
            redirect-uri: http://43.200.175.236/oauth2/kakao
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

cookie:
  expiration: 3600
  domain: 52.78.56.248
  max-age: 300
  access-name: ac_t
  refresh-name: rf_t

frontend:
  auth-redirect-url: http://43.200.175.236/loading
  base-url: http://43.200.175.236/
  allowance-redirect-url: http://43.200.175.236/login/term

backend:
  base-url: http://43.200.175.236/
